location: .gitman
sources:
  - repo: https://github.com/LASER-Robotics/open_vins
    name: open_vins
    rev: master
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/open_vins
    scripts:
      - git submodule update --init --recursive
  - repo: git@github.com:LASER-Robotics/laser_vins_imu_filter.git
    name: laser_vins_imu_filter
    rev: refactor
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/laser_vins_imu_filter
    scripts:
      - git submodule update --init --recursive
  - repo: git@github.com:LASER-Robotics/laser_vins_republisher.git
    name: laser_vins_republisher
    rev: refactor
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/laser_vins_republisher
    scripts:
      - git submodule update --init --recursive
default_group: ''
groups:
  -
