root: ./
name: simulation
startup_window: open_vins
pre_window: export UAV_NAME=uav1; export UAV_TYPE=x500
windows:
  - spawn:
      layout: even-horizontal
      panes:
        - ros2 launch laser_uav_simulation gazebo.launch.py world:=$(ros2 pkg prefix laser_gazebo_resources)/share/laser_gazebo_resources/worlds/forest 
        - ros2 launch laser_uav_simulation spawn_drones.launch.py spawn_drones_file:=./configs/spawn.yaml
  - px4_api:
      layout: tiled
      panes:
        - sleep 1; ros2 launch laser_uav_px4_api api.launch.py api_file:="./configs/api.yaml"
  - estimation_manager:
      layout: tiled
      panes:
        - sleep 1; ros2 launch laser_uav_managers estimation_manager.launch.py params_file:="./configs/estimation_manager.yaml"
  - control_manager:
      layout: tiled
      panes:
        - sleep 1; ros2 launch laser_uav_managers control_manager.launch.py
        - 'history -s ros2 service call /$UAV_NAME/px4_api/arm std_srvs/srv/Trigger {}'
        - 'history -s ros2 service call /$UAV_NAME/control_manager/takeoff std_srvs/srv/Trigger {}'
        - 'history -s ros2 service call /$UAV_NAME/control_manager/land std_srvs/srv/Trigger {}'
  - open_vins:
      layout: tiled
      panes:
        - ros2 launch laser_open_vins_core open_vins.launch.py
          open_vins_params_folder:=bluefox_simulation
          topic_camera0:=/$UAV_NAME/vio_sensor/image_raw
          topic_imu:=/$UAV_NAME/vio_sensor/imu
  - vins_republisher:
      layout: tiled
      panes:
        - ros2 launch laser_vins_republisher vins_republisher.launch.py 
  - odometry:
      layout: even-horizontal
      panes:
        - sleep 6; ros2 topic echo --no-arr /$UAV_NAME/ground_truth
        - sleep 6; ros2 topic echo --no-arr /$UAV_NAME/estimation_manager/estimation
  - goto:
      layout: tiled 
      panes:
        - 'history -s ros2 topic pub -1 /$UAV_NAME/control_manager/goto laser_msgs/msg/PoseWithHeading \"{position: {x: 0.0, y: 0.0, z: 1.5}, heading: 0.0}\"'
  - rviz:
      layout: tiled
      panes:
        - sleep 10; ros2 launch laser_open_vins_core rviz.launch.py
